
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-6pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-6pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjM4OTAxMzc1","is_bot":false,"login":"luxiangzh","name":"Luxiang Zhang"},"headRefName":"LZ-MenuItemReview-Form","number":68,"title":"Add MenuItemReview Form","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/68"},{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-helpRequestForm","number":67,"title":"Rv help request form","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/67"},{"author":{"id":"U_kgDOBaDySw","is_bot":false,"login":"AdmPenguin","name":"Bao T."},"headRefName":"bt-UCSBOrganizationForm","number":66,"title":"UCSB Organization Fixture, Form, Table","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/66"},{"author":{"id":"MDQ6VXNlcjM4OTAxMzc1","is_bot":false,"login":"luxiangzh","name":"Luxiang Zhang"},"headRefName":"LZ-MenuItemReview-Fixtures","number":65,"title":"Create MenuItemReview Fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/65"},{"author":{"id":"MDQ6VXNlcjM4OTAxMzc1","is_bot":false,"login":"luxiangzh","name":"Luxiang Zhang"},"headRefName":"LZ-MenuItemReview-Backend","number":64,"title":"Add MenuItemReview Backend from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/64"},{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-helpRequestFixtures","number":63,"title":"Rv help request fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/63"},{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-helpRequest","number":62,"title":"pull team02 helprequest and create working personal deployment","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/62"}]
