
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-6pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-6pm-4
pull_requests: [{"author":{"id":"U_kgDOBtxmKA","is_bot":false,"login":"Aavash-Adhikari","name":""},"headRefName":"aa-articles","number":78,"title":"Aa articles","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/78"},{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-helpRequestForm","number":67,"title":"Rv help request form","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/67"},{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-helpRequestFixtures","number":63,"title":"Rv help request fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/63"},{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-helpRequest","number":62,"title":"pull team02 helprequest and create working personal deployment","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-4/pull/62"}]
